# Generated by Django 5.0.6 on 2024-05-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pointage_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
