# Generated by Django 5.0.6 on 2024-05-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hours_per_week',
            field=models.IntegerField(default=0),
        ),
    ]
