# Generated by Django 5.0.6 on 2024-06-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role_serviceconstraints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceconstraints',
            old_name='end_time',
            new_name='friday_end',
        ),
        migrations.RenameField(
            model_name='serviceconstraints',
            old_name='start_time',
            new_name='friday_start',
        ),
        migrations.RemoveField(
            model_name='serviceconstraints',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='serviceconstraints',
            name='required_employees',
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='monday_end',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='monday_start',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='saturday_end',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='saturday_start',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='sunday_end',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='sunday_start',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='thursday_end',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='thursday_start',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='tuesday_end',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='tuesday_start',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='wednesday_end',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='wednesday_start',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
    ]
