# Generated by Django 5.0.6 on 2024-06-03 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_employeerequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi'), ('Saturday', 'Samedi'), ('Sunday', 'Dimanche')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('required_employees', models.PositiveIntegerField()),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requirements', to='accounts.serviceconstraints')),
            ],
        ),
    ]
