# Generated by Django 5.0.6 on 2024-06-03 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_shiftrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequirement',
            name='employees_required',
        ),
        migrations.RemoveField(
            model_name='employeerequirement',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='employeerequirement',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('employees_required', models.IntegerField()),
                ('employee_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.employeerequirement')),
            ],
        ),
    ]
