# Generated by Django 5.0.6 on 2024-06-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_employeerequirement_employees_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconstraints',
            name='max_consecutive_work_hours',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='max_work_hours_per_day',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='min_break_minutes',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
