# Generated by Django 5.0.6 on 2024-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_schedule_scheduleentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
