# Generated by Django 5.0.6 on 2024-07-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
