# Generated by Django 5.0.6 on 2024-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customuser_photo_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_lead', 'Team Lead')], default='manager', max_length=10),
        ),
    ]
