# Generated by Django 5.0.6 on 2024-08-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceconstraints',
            name='max_work_hours_per_week',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('user', 'start_date', 'end_date')},
        ),
    ]
