# Generated by Django 5.0.6 on 2024-08-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_notification_options_notification_redirect_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconstraints',
            name='min_consecutive_rest_days',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='serviceconstraints',
            name='max_work_hours_per_week',
            field=models.IntegerField(default=40),
        ),
    ]
